ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS validation_report TEXT;
ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS ocr_metrics TEXT;

CREATE TABLE public.summary_feedbacks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id integer NOT NULL,
    user_id integer NOT NULL,
    is_helpful boolean NOT NULL,
    comment TEXT,
    model_name character varying(100),
    prompt_version character varying(50),
    created_at timestamp(6) with time zone,
    CONSTRAINT fk_feedback_document FOREIGN KEY (document_id)
        REFERENCES public.documents(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_feedback_user FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT unique_feedback_per_user UNIQUE (document_id, user_id)
);

CREATE INDEX idx_summary_feedbacks_document ON public.summary_feedbacks(document_id);
CREATE INDEX idx_summary_feedbacks_model ON public.summary_feedbacks(model_name);
